// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations run DDL, which is unreliable through a transaction-mode pooler
    // (PgBouncer / the Neon pooler). Hosts that give you a pooled URL also give you
    // a direct one — put that in DIRECT_URL and the CLI will prefer it, while the
    // app keeps using the pooled DATABASE_URL at runtime.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
